# GitLab CI/CD Pipeline for vertex

stages:
  - build
  - release

variables:
  GO_VERSION: "1.23"
  PROJECT_NAME: "service-manager"
  OUTPUT_DIR: "dist"
  CGO_ENABLED: "0"

default:
  image: node:20
  before_script:
    - apt-get update && apt-get install -y golang-${GO_VERSION}
    - export PATH="/usr/lib/go-${GO_VERSION}/bin:$PATH"
    - mkdir -p $OUTPUT_DIR

build:
  stage: build
  script:
    - cd web
    - npm ci
    - npm run build
    - cd ..
    - go mod tidy
    - mkdir -p $OUTPUT_DIR
    - GOOS=linux   GOARCH=amd64 go build -o $OUTPUT_DIR/${PROJECT_NAME}-linux-amd64
    - GOOS=windows GOARCH=amd64 go build -o $OUTPUT_DIR/${PROJECT_NAME}-windows-amd64.exe
    - GOOS=darwin  GOARCH=amd64 go build -o $OUTPUT_DIR/${PROJECT_NAME}-darwin-amd64

release:
  stage: release
  only:
    - tags
  script:
    - echo "# Release $CI_COMMIT_TAG" > release-notes.md
    - echo "" >> release-notes.md
    - echo "## 🚀 Features" >> release-notes.md
    - echo "- Cross-platform service manager for NeST microservices" >> release-notes.md
    - echo "- Embedded React web interface" >> release-notes.md
    - echo "- Real-time logs and status" >> release-notes.md
    - echo "" >> release-notes.md
    - echo "## 📦 Downloads" >> release-notes.md
    - echo "" >> release-notes.md
    - ls -lh $OUTPUT_DIR
    - echo "| Platform | Arch | Binary |" >> release-notes.md
    - echo "|----------|------|--------|" >> release-notes.md
    - >
      for f in $OUTPUT_DIR/${PROJECT_NAME}-*; do
        platform=$(echo "$f" | cut -d '-' -f3);
        arch=$(echo "$f" | cut -d '-' -f4 | cut -d '.' -f1);
        binary=$(basename "$f");
        echo "| $platform | $arch | \`$binary\` |" >> release-notes.md;
      done
    - cat release-notes.md
    - >
      curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
           --data-urlencode "name=NeST Release $CI_COMMIT_TAG" \
           --data-urlencode "tag_name=$CI_COMMIT_TAG" \
           --data-urlencode "description=$(cat release-notes.md)" \
           "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/releases"
