#!/bin/bash
# Common Environment Variables for NeST Microservices
# Generated by NeST Service Manager on 2025-07-27 08:04:27

# Profile and Feature Flags
export ACTIVE_PROFILE='dev'
export APM_ENABLED='false'

# Config Server Settings
export CONFIG_USERNAME='nest'
export CONFIG_PASSWORD='1kzwjz2nzegt3nest@ppra.go.tza1q@BmM0Oo'
export CONFIG_SERVER='nest-config-server'

# Common Client ID
export CLIENT_ID='nest'

# Service Database Names
export DB_NAME_UAA='nest_uaa'
export DB_NAME_APP='nest_app'
export DB_NAME_CONTRACT='nest_contract'
export DB_NAME_DSMS='nest_dsms'

# Service Ports
export SERVICE_PORT_REGISTRY='8800'
export SERVICE_PORT_CONFIG='8801'
export SERVICE_PORT_GATEWAY='8802'
export SERVICE_PORT_UAA='8803'
export SERVICE_PORT_APP='8805'
export SERVICE_PORT_CONTRACT='8818'
export SERVICE_PORT_DSMS='8812'

# Discovery Server
export DISCOVERY_SERVER='nest-registry-server'
export DEFAULT_ZONE='http://nest-registry-server:8800/eureka/'

# Database Settings
export DB_HOST='localhost'
export DB_PORT='5432'
export DB_USER='postgres'
export DB_PASS='P057gr35'

# Gateway
export GATE_WAY='nest-gateway'

# RabbitMQ Settings
export RABBIT_HOSTNAME='localhost'
export RABBIT_PORT='5672'
export RABBIT_USERNAME='rabbitmq'
export RABBIT_PASSWORD='R@bb17mq'

# Redis Settings
export REDIS_HOST='localhost'
export REDIS_USER='default'
export REDIS_PASS='mypassword'

echo "✅ NeST common environment variables loaded successfully"
